create database customer_behavior
use customer_behavior

select * from customer_behavior

--- what is the total revenue generated by male vs female cutomer
select gender, sum(purchase_amount) as revenue
from customer_behavior
group by gender

---2 which customer used a discount but still more than the average purchase amount
select customer_id, purchase_amount 
from customer_behavior
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer_behavior)

---3 which are the top 5 products with the highest average review rating
select item_purchased,avg(review_rating)as "Average Product Rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc

---4 Compare the average Purchase amount between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

---5 Do suscribed customer spend more? compare average spend and total revenue 
--- between suscribers and non-suscribers.
select subscription_status,
count (customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue,avg_spend desc;

---6 which 5 product have the highest percentage of purchase with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2)as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc

---7 Segment customer into new, returning, and loyal based on their total 
--- number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
    from customer_behavior
)
select customer_segment, count(*) as "Number of customer"
from customer_type
group by customer_segment

---8 what are the top 3 most purchased products within each category

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--- Are customers who are repeat buyers (more than 5 purchases ) also likely to subscribe
select subscription_status,
count (customer_id) as repeat_buyers
from customer_behavior
where previous_purchases > 5
group by subscription_status

---10 what is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;

    
